ARG JENKINS_IMAGE_TAG={{ jenkins_image_tag }}

FROM jenkins/jenkins:${JENKINS_IMAGE_TAG}

USER root

RUN groupadd -g {{ jenkins_docker_gid.stdout }} docker \
    && usermod -aG docker jenkins

USER jenkins
